- hosts: all
  become: yes
  tasks:

    - name: install Sudo
      apt:
        name: sudo
        state: present
        update_cache: true

    - name: allow 'james' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'james ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Setup authorized SSH Key
      authorized_key: user=james key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Install Python3
      command: apt-get install python3
      